### ISSUE TITLE
DracoClaw Ideas Masterpost

### ISSUE THREAD

**Issue by DracoClaw** [IRicTheCoder/ViktorsDiskoveries#1]
I will fill out this for for each idea as a comment.

**What will this feature do?**
A clear and concise description of what this feature should do

**How it should integrate into the mod? (Optional)**
A clear and concise description of how this should integrate with the mod

**Possible names for the feature? (Optional)**
If you wish to, please give some names for this feature

**Additional context**

**Comment by DracoClaw** [comment]
Silo Link

Like a Refinery Link, this allows to remotely deposit to a silo.
This will improve automation as it allows drones in other areas to collect food items for example and send them directly to a silo, allowing for food automation.

This can be an upgrade applied to a silo and then linked to an available silo link.

**Comment by DracoClaw** [comment]
Drone White/Black Listing

Allows to set up a blacklist or multi item whitelist of a specific item. Lets say you are trying to collect a specific plort for science, this lets you tell your drones to keep collecting all the plorts but not these specific ones.

**Comment by DracoClaw** [comment]
Single Silo Port

Creates one port on a silo, allowing you to cycle through all the items and take them out from one spot. Also it allows you to input all items into one spot. No need to run around your silo and switch slots to find what you need.

**Comment by DracoClaw** [comment]
More Inventory

More inventory slots for the player. Four slots are just not enough.

Would be purchasable for each slot. Each slot costs X amount to add and the price goes up for each one.

**Comment by DracoClaw** [comment]
More Storage

Adds more slots to a silo. 12 slots when there are 18 food types makes no sense. There are even 13 favored food types, so adding even one more slot per side would make a huge difference.

**Comment by DracoClaw** [comment]
Drones work with warp links

It makes no sense why Drones can not interact with warp links. Let them move things around!

**Comment by DracoClaw** [comment]
Advanced Mapping

(Not storage or automation, but I feel like Viktor would be interested in this.)

Let's update the map, The wilds goes unmarked, key points are missing, and there is no way to mark things yourself. The slimepedia book has an interesting map that has details and key points written on top of it.

**Comment by DracoClaw** [comment]
Advanced Auto Feeder

An Auto Feeder upgrade that highly improves the feeder.

Checks how many slimes are in the corral, and dispenses the correct amount of food. Has a vac that will suck in any non eaten food right before the next dispense cycle, this prevents buildup of food as well as waste. 

Maybe a second input? largos have multiple favorites after all. This slot could have a significant less amount of space, acting as a backup more than anything.

**Comment by RicardoTheCoder** [comment]
So far everything marked with a 👍 I had already plans for something similar. The one marked with 😕 i'm not sure if it would be something I would do. But I will keep it in mind.

**Comment by DracoClaw** [comment]
Hen Collectors

Like the collectors that Mochi gives you, but it collects regular Hen and Roostros.

It can then spit some of each back out to keep your coop going.

**Comment by DracoClaw** [comment]
Better Teleporters

The teleport will now show the icon of the biome its in so you know where it leads.

Multi/Mosaic Teleport

One teleport that gives you access to the rest.

It either opens a menu that lets you choose where to go, or it has a button that will just cycle through the options.

In addition, the teleport when placing it down, will ask you to assign it a name, so on the list it will show the name, the icon of the biome, and the color of the teleporter.

**Comment by DracoClaw** [comment]
Decorizer Link

I cant be the only one who carries a market and refinery link on them for quick deposits while out in the range. a decorizer can work the same. you find an echo but dont have space just deposit it right away!

**Comment by DracoClaw** [comment]
Advanced Chime Changer/Chime Tuner

Either an upgrade to the Chime Changer, a separate Chime Tuner, or possibly even a 'tuning fork' that takes Chimes and Carol Echos and allows you to adjust their key. If this seems OP possibly have a cost of Newbucks or something else.

Something else that would be nice, but is probably too much, allowing to change the instrument of individual Chimes and Carol Echos.

**Comment by RicardoTheCoder** [comment]
> Advanced Chime Changer/Chime Tuner
> 
> Either an upgrade to the Chime Changer, a separate Chime Tuner, or possibly even a 'tuning fork' that takes Chimes and Carol Echos and allows you to adjust their key. If this seems OP possibly have a cost of Newbucks or something else.
> 
> Something else that would be nice, but is probably too much, allowing to change the instrument of individual Chimes and Carol Echos.

Not sure about this one, but I will look into it to see if this is easy to make happen

**Comment by Spinyspino8** [comment]
I think the drones interacting with warp links is an awesome idea! actually realized they cant the other day when trying to move my silver parsnips and found It really annoying.
