### ISSUE TITLE
Discord Rich Presence Not Translating

### ISSUE THREAD

**Issue by KomiksPL** [IRicTheCoder/ViktorsDiskoveries#32]
# Bug Report

## Describe the bug

Rich Presence status is not working properly

## To Reproduce
*Steps to reproduce the behavior:*

1. Go to Slime Rancher
2. Change to non-native language with a translated Base folder
3. Check Status on Discord

## Expected behavior
The Rich Presence should properly display in the selected language.

## Screenshots
![Bez tytułu1](https://user-images.githubusercontent.com/44307026/92261768-55eb8100-eeda-11ea-8ec4-c4ba30ca3810.png)
![image](https://user-images.githubusercontent.com/44307026/92261782-5c79f880-eeda-11ea-944c-acecc103f4e0.png)

### Other Mods
Nothing

### Game Version
1.4.2

### Mod Version
Albino Update

**Comment by RicardoTheCoder** [comment]
This might be related to some weird hardcoded language selection for the Rich Presence, haven't found out where it is at but I do believe it can be patched and fixed. Will look into it further.

**Comment by Atmudia** [comment]
I fixed it
